# Generated by Django 5.1.3 on 2024-12-02 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('period', models.CharField(max_length=255, verbose_name='Период')),
                ('main_page_content', models.TextField(verbose_name='Главная страница')),
                ('methodology_file', models.FileField(blank=True, null=True, upload_to='general_info/', verbose_name='Методология')),
                ('charter_file', models.FileField(blank=True, null=True, upload_to='general_info/', verbose_name='Уставные документы')),
                ('results_file', models.FileField(blank=True, null=True, upload_to='general_info/', verbose_name='Результаты старых рейтингов')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email пользователя')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_for_newsletters', models.EmailField(max_length=254, verbose_name='Email для рассылки новостей HR2K')),
                ('company_name_full', models.CharField(max_length=255, verbose_name='Название компании (полное)')),
                ('company_name_short', models.CharField(max_length=20, verbose_name='Название компании (краткое)')),
                ('company_logo', models.ImageField(upload_to='company_logos/', verbose_name='Логотип компании')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Почтовый индекс')),
                ('postal_address', models.TextField(verbose_name='Почтовый адрес')),
                ('responsible_email', models.EmailField(max_length=254, verbose_name='Email ответственного')),
                ('responsible_name', models.CharField(max_length=255, verbose_name='Имя и фамилия ответственного')),
                ('responsible_phone', models.CharField(max_length=15, verbose_name='Телефон ответственного')),
                ('consent_data_processing', models.BooleanField(default=False, verbose_name='Согласие на обработку данных')),
                ('confirmation', models.BooleanField(default=False, verbose_name='Подтверждение условий')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Фирменное наименование')),
                ('company_address', models.TextField(verbose_name='Адрес головного офиса')),
                ('specialization', models.TextField(verbose_name='Основная специализация')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Совокупная выручка')),
                ('submission_date', models.DateField(auto_now_add=True, verbose_name='Дата заполнения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPositioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255, verbose_name='Позиционирование')),
                ('revenue_share', models.PositiveIntegerField(verbose_name='Распределение выручки (%)')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionings', to='website.companysurvey')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255, verbose_name='Название компании/отдела')),
                ('employee_count', models.PositiveIntegerField(verbose_name='Количество сотрудников')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='website.companysurvey')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=255, verbose_name='Название премии')),
                ('award_category', models.CharField(max_length=50, verbose_name='Категория премии')),
                ('award_type', models.CharField(max_length=50, verbose_name='Тип награды')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='website.companysurvey')),
            ],
        ),
    ]
