# Generated by Django 5.1.3 on 2024-12-05 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysurvey',
            name='company_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст компании (лет)'),
        ),
        migrations.AddField(
            model_name='companysurvey',
            name='geography_activity',
            field=models.CharField(choices=[('federal', 'Федеральный уровень'), ('regional', 'Региональный уровень')], default='federal', max_length=20, verbose_name='География активности'),
        ),
        migrations.CreateModel(
            name='CompanyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_count', models.PositiveIntegerField(verbose_name='Количество мероприятий')),
                ('audience', models.CharField(max_length=255, verbose_name='Аудитория')),
                ('participant_count', models.PositiveIntegerField(verbose_name='Количество участников')),
                ('event_format', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Оффлайн'), ('hybrid', 'Гибридный')], max_length=10, verbose_name='Формат проведения')),
                ('event_type', models.CharField(max_length=255, verbose_name='Формат мероприятия')),
                ('participation_type', models.CharField(choices=[('speaker', 'Спикер'), ('participant', 'Участник'), ('organizer', 'Организатор')], max_length=15, verbose_name='Тип участия')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='website.companysurvey', verbose_name='Анкета')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН компании')),
                ('ownership_share', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Доля владения (%)')),
                ('buying_share', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Доля баинга в выручке (%)')),
                ('revenue_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Доля выручки (тыс. рублей)')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='website.companysurvey', verbose_name='Анкета')),
            ],
        ),
    ]
