# Generated by Django 5.1.3 on 2024-12-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_companysurvey_company_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysurvey',
            name='num_certificates',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество сертификатов'),
        ),
        migrations.AddField(
            model_name='companysurvey',
            name='num_employees_in_communications',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество сотрудников, работающих в коммуникациях более 3 лет'),
        ),
        migrations.AddField(
            model_name='companysurvey',
            name='num_employees_over_3_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество сотрудников, работающих более 3 лет'),
        ),
        migrations.AddField(
            model_name='companysurvey',
            name='num_expert_employees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество сотрудников-экспертов'),
        ),
        migrations.AddField(
            model_name='companysurvey',
            name='num_government_awards',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество государственных наград'),
        ),
    ]
