# Generated by Django 5.1.3 on 2024-12-06 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_companysurvey_num_certificates_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companysurvey',
            name='moderator_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий модератора'),
        ),
        migrations.AddField(
            model_name='companysurvey',
            name='user_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий пользователя'),
        ),
        migrations.CreateModel(
            name='SurveyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Заполнение'), ('moderation', 'На модерации'), ('revision', 'На доработке'), ('accepted', 'Принят')], max_length=20, verbose_name='Статус')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='website.companysurvey')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Статусы анкеты',
                'ordering': ['-timestamp'],
            },
        ),
    ]
