# Generated by Django 5.1.3 on 2024-12-08 22:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_companysurvey_moderator_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveystatus',
            options={},
        ),
        migrations.RemoveField(
            model_name='surveystatus',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='surveystatus',
            name='user',
        ),
        migrations.AddField(
            model_name='surveystatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата установки статуса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveystatus',
            name='status',
            field=models.CharField(choices=[('moderate', 'На модерации'), ('return', 'На доработку'), ('approved', 'Принят'), ('rejected', 'Отклонено')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='surveystatus',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='website.companysurvey', verbose_name='Анкета'),
        ),
    ]
