# Generated by Django 5.1.3 on 2024-12-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_surveystatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysurvey',
            name='company_address',
            field=models.CharField(max_length=255, verbose_name='Адрес головного офиса'),
        ),
        migrations.AlterField(
            model_name='companysurvey',
            name='specialization',
            field=models.CharField(max_length=255, verbose_name='Основная специализация'),
        ),
    ]
