# Generated by Django 5.1.3 on 2024-12-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_surveystatus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='postal_address',
            field=models.CharField(max_length=255, verbose_name='Почтовый адрес'),
        ),
    ]
