# Generated by Django 5.1.4 on 2024-12-18 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_companyawards_award_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='survey_file',
            field=models.FileField(blank=True, null=True, upload_to='survey_docs/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='companyawards',
            name='award_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория премии'),
        ),
        migrations.AlterField(
            model_name='companyawards',
            name='award_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название премии'),
        ),
        migrations.AlterField(
            model_name='companyawards',
            name='award_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип награды'),
        ),
        migrations.AlterField(
            model_name='companyemployees',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании/отдела'),
        ),
        migrations.AlterField(
            model_name='companyemployees',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество сотрудников'),
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='audience',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='event_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество мероприятий'),
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='event_format',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Оффлайн')], max_length=10, null=True, verbose_name='Формат проведения'),
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='event_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Формат мероприятия'),
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='participant_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество участников'),
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='participation_type',
            field=models.CharField(choices=[('organizer', 'Организатор'), ('sooorganizer', 'Со-организатор')], max_length=15, null=True, verbose_name='Тип участия'),
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='website.companysurvey', verbose_name='Анкета'),
        ),
        migrations.AlterField(
            model_name='companypositioning',
            name='revenue_share',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Распределение выручки (%)'),
        ),
        migrations.AlterField(
            model_name='companypositioning',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Позиционирование'),
        ),
        migrations.AlterField(
            model_name='companyrevenue',
            name='buying_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Доля баинга в выручке (%)'),
        ),
        migrations.AlterField(
            model_name='companyrevenue',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='companyrevenue',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН компании'),
        ),
        migrations.AlterField(
            model_name='companyrevenue',
            name='ownership_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Доля владения (%)'),
        ),
        migrations.AlterField(
            model_name='companyrevenue',
            name='revenue_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Доля выручки (тыс. рублей)'),
        ),
        migrations.AlterField(
            model_name='companyrevenue',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='website.companysurvey', verbose_name='Анкета'),
        ),
        migrations.AlterField(
            model_name='companysurvey',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес головного офиса'),
        ),
        migrations.AlterField(
            model_name='companysurvey',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фирменное наименование'),
        ),
        migrations.AlterField(
            model_name='companysurvey',
            name='geography_activity',
            field=models.CharField(blank=True, choices=[('federal', 'Федеральный уровень'), ('regional', 'Региональный уровень')], default='federal', max_length=20, null=True, verbose_name='География активности'),
        ),
        migrations.AlterField(
            model_name='companysurvey',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Основная специализация'),
        ),
        migrations.AlterField(
            model_name='companysurvey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surveystatus',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('moderate', 'На модерации'), ('return', 'На доработку'), ('approved', 'Принят'), ('rejected', 'Отклонено')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
