# Generated by Django 5.1.4 on 2024-12-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_companyprofile_survey_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='survey_file',
        ),
        migrations.AddField(
            model_name='companysurvey',
            name='survey_file',
            field=models.FileField(blank=True, null=True, upload_to='survey_docs/', verbose_name='File'),
        ),
    ]
