# Generated by Django 5.1.4 on 2024-12-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_companyprofile_survey_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyevent',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название мероприятия'),
        ),
    ]
