# Generated by Django 5.1.4 on 2024-12-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_companyevent_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysurvey',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='survey_docs/', verbose_name='Заверенный документ'),
        ),
        migrations.AddField(
            model_name='companysurvey',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='survey_docs/', verbose_name='Логотип'),
        ),
    ]
